# Generated by Django 4.2.7 on 2025-11-09 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('favorite_color', models.CharField(blank=True, max_length=50)),
                ('favorite_food', models.CharField(blank=True, max_length=100)),
                ('favorite_movie', models.CharField(blank=True, max_length=200)),
                ('favorite_song', models.CharField(blank=True, max_length=200)),
                ('favorite_place', models.CharField(blank=True, max_length=200)),
                ('hobbies', models.TextField(blank=True)),
                ('relationship_anniversary', models.DateField(blank=True, null=True)),
                ('love_language', models.CharField(blank=True, max_length=100)),
                ('personal_notes', models.TextField(blank=True)),
                ('share_bio', models.BooleanField(default=False)),
                ('share_birthday', models.BooleanField(default=False)),
                ('share_location', models.BooleanField(default=False)),
                ('share_phone', models.BooleanField(default=False)),
                ('share_favorite_color', models.BooleanField(default=False)),
                ('share_favorite_food', models.BooleanField(default=False)),
                ('share_favorite_movie', models.BooleanField(default=False)),
                ('share_favorite_song', models.BooleanField(default=False)),
                ('share_favorite_place', models.BooleanField(default=False)),
                ('share_hobbies', models.BooleanField(default=False)),
                ('share_relationship_anniversary', models.BooleanField(default=False)),
                ('share_love_language', models.BooleanField(default=False)),
                ('share_personal_notes', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
