# Generated by Django 4.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_deletion_approved_by_note_deletion_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_shared',
            field=models.BooleanField(default=True),
        ),
    ]

