# Generated by Django 4.2.7 on 2025-01-XX XX:XX

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_journalentry_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='edit_approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the edit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='edit_requested_by',
            field=models.ForeignKey(blank=True, help_text='User who requested to edit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='pending_content',
            field=models.TextField(blank=True, help_text='Pending content change', null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='pending_title',
            field=models.CharField(blank=True, help_text='Pending title change', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='deletion_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_deletion_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='deletion_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_deletion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='edit_approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the edit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_edit_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='edit_requested_by',
            field=models.ForeignKey(blank=True, help_text='User who requested to edit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_edit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='pending_content',
            field=models.TextField(blank=True, help_text='Pending content change', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='pending_title',
            field=models.CharField(blank=True, help_text='Pending title change', max_length=200, null=True),
        ),
    ]

